### ISSUE TITLE
Replace drupal HTTP requests with Northstar PHP

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/TeamRocket#11]
@jessleenyc commented on [Mon Sep 26 2016](https://github.com/DoSomething/northstar/issues/440)

**Comment by jessleenyc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(13) As an admin, I want to start using Northstar-PHP so that we can make OAuth requests from Phoenix in the future.](https://trello.com/c/u67qDvWL/32-13-as-an-admin-i-want-to-start-using-northstar-php-so-that-we-can-make-oauth-requests-from-phoenix-in-the-future)

**Comment by jessleenyc** [comment]
@DFurnes is there anything left to do for this issue?

**Comment by DFurnes** [comment]
Yep, there are still a few remaining calls to the old `_dosomething_northstar_build_http_client` method. I believe Diego has a local branch with that work in progress.

**Comment by weerd** [comment]
@jessleenyc I ran into some issues with this, and now that there's been further progress on pushing NS-PHP (now `Gateway`) further in preparation for usage in Rogue, the stuff I was working on needs to be reworked and updated to match the latest changes in the library. I'm going to step off this for now until `Gateway` is more settled in with all the latest changes and then jump back on it. Switching gears to the translation related issues for now.

**Comment by jessleenyc** [comment]
@weerd got it, thanks!
