### ISSUE TITLE
Remove historical onboarding data tracking

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/TeamRocket#31]

**Comment by jessleenyc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) As an engineer, I want to remove historical data tracking so that we can reduce the amount of requests we're making and clean up the code.](https://trello.com/c/X4YvF5yY/44-1-as-an-engineer-i-want-to-remove-historical-data-tracking-so-that-we-can-reduce-the-amount-of-requests-we-re-making-and-clean-u)

**Comment by deadlybutter** [comment]
Duplicated https://github.com/DoSomething/TeamRocket/issues/28
