### ISSUE TITLE
Dynamically update gallery likes from the likes received in onboarding

### ISSUE THREAD

**Issue by jessleenyc** [DoSomething/TeamRocket#7]
@jessleenyc commented on [Thu Aug 25 2016](https://github.com/DoSomething/phoenix/issues/6952)

_FEATURE OVERVIEW_
-------------------
#### User Story
As a user, if I liked a photo in onboarding, I want to see that reflected in the gallery when I scroll down in the action page. 

#### Additional Information (optional)
Since we're not using React to create the RB items in the Reportback gallery, we can't dynamically update RB items in gallery if the rb is liked in onboarding. 

#### Why This Matters
This can be confusing to the user and they should see that the photo they liked, is liked everywhere. 

---

@deadlybutter commented on [Thu Aug 25 2016](https://github.com/DoSomething/phoenix/issues/6952#issuecomment-242523831)

Wait, have we tested / observed this? Im not sure why the API would return differently based on onboarding / campaign template / user profile, it uses the same data?

---

@deadlybutter commented on [Thu Aug 25 2016](https://github.com/DoSomething/phoenix/issues/6952#issuecomment-242524269)

OH now i get it...

---

@weerd commented on [Thu Aug 25 2016](https://github.com/DoSomething/phoenix/issues/6952#issuecomment-242527974)

:trollface: I've had it happen to me while working on Reactions on local development.

**Comment by jessleenyc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user, if I like a photo during onboarding, I want that like to appear in the gallery without refreshing the page.](https://trello.com/c/6SEvulsv/30-as-a-user-if-i-like-a-photo-during-onboarding-i-want-that-like-to-appear-in-the-gallery-without-refreshing-the-page)

**Comment by ngjo** [comment]
closing this -- can revisit when we look at the campaign template
